### ISSUE TITLE
Changes to elements lost after publishing page

### ISSUE THREAD

**Issue by LABCAT** [dnadesign/silverstripe-elemental#631]
if I some content to an element:
![image](https://user-images.githubusercontent.com/9105153/54396529-23fbc300-4718-11e9-9bfc-15f9eb675413.png)

Then click the click the publish button, the content updates and the preview updates:
![image](https://user-images.githubusercontent.com/9105153/54396629-86ed5a00-4718-11e9-8764-4059a9304b2e.png)

However if you then open the element again the content changes are not reflected in the editor:
![image](https://user-images.githubusercontent.com/9105153/54396784-08dd8300-4719-11e9-8e9b-84a746db5fd8.png)

This also means that if you publish the page then your changes are lost:
![image](https://user-images.githubusercontent.com/9105153/54396813-2dd1f600-4719-11e9-977a-eee24c1a6bb2.png)

If you refresh the page then the content actually appears in the content editor as it should.

**Comment by robbieaverill** [comment]
@LABCAT can you please provide the versions of core and elemental modules you're using? `composer show | grep -E "(silverstripe\/admin|silverstripe-elemental)"`

**Comment by LABCAT** [comment]
Here are the results of that command

dnadesign/silverstripe-elemental          
4.0.3   Elemental pagetype and collection of Elements
silverstripe/admin                        
1.3.2   SilverStripe admin interface


recipe-cms version is 4.3.2

**Comment by brynwhyman** [comment]
I've just reproduced this too. Here's my steps:
```
dnadesign/silverstripe-elemental 4.0.3 
silverstripe/recipe-cms 4.3.2 
```

1. Create a blocks page, add a content block
2. Expand the block, add some content, publish at the page level
3. Identify that content is published correctly and block is collapsed
4. Identify that the collapsed block summary is correct
5. Expand the block and identify the content is lost (bug)

**Comment by satrun77** [comment]
This might be useful. 

I'm using elemental **4.0.2** & silverstripe/recipe-cms **4.3.1**, which does not seem to have this issue.

**Comment by tomstgeorge** [comment]
I'm also seeing this issue on:

dnadesign/silverstripe-elemental            4.0.3             
silverstripe/admin                                      1.3.0

**Comment by ScopeyNZ** [comment]
Thanks for all the reports everyone. It's genuinely is really helpful to see what problems are affecting people the most. We'll be looking at this very soon (probably this week).

**Comment by ScopeyNZ** [comment]
Ok I think this is an issue that past me identified and resolved - in the `silverstripe/admin` repo.

Way back (read "one month") I committed this patch: https://github.com/silverstripe/silverstripe-admin/commit/ff05047a5dc17aadec38a8a6eb6208742b025e92

Commit message here for ease:

> FIX Deferring events on mount and ensuring events are triggered on change in HtmlEditorField

`HtmlEditorField` is the TinyMCE field.

This patch was released in a stable version yesterday (4.3.3).

With either this stable version or the `silverstripe/admin` dev branch for the next patch release (`4.3.x-dev`) **I cannot reproduce this issue**. 

I'm pretty sure we had something in this module to workaround this bug in admin, but our fix had unintended side effects so needed to be removed. Unfortunately that means 4.0.3 of elemental relies on 1.3.3 of admin to ensure a non-buggy behaviour.

**Comment by ScopeyNZ** [comment]
Ok I've just spent a little time being double sure. Here's the reference PR in silverstripe/admin for future reference: https://github.com/silverstripe/silverstripe-admin/pull/822

I'll close this issue as resolved. Update your admin dependency to `1.3.3` - this should be compatible with framework/cms `4.3` at any patch version.

**Comment by Zazama** [comment]
Hello, I'm not sure if I should create another issue because this is closed,
but using admin 1.3.3, framework/cms 4.3.3 and elemental 4.0.3,
this issue still exists on **UploadFields** for me.

After changing an image and publishing, the image is reversed to the old one but after a F5 refresh, it's the correct one.

**Comment by kinglozzer** [comment]
Thanks @Zazama, the issue with `UploadField` has also been fixed but that hasn’t been released yet. It will be released as part of `silverstripe/asset-admin 1.3.4`

**Comment by tomstgeorge** [comment]
I'm also seeing the same issue with **DateFields** - updates not showing in the CMS until you refresh the page. 

using admin 1.3.3, framework/cms 4.3.3 and elemental 4.0.3

**Comment by ScopeyNZ** [comment]
🤔 This should just be using the default browser UI for date fields. I can't imagine how that's any different from just any text input. Just making sure that you're not using a custom date field module to replace the browser UI?

If not, can you also provide the browsers that you see this problem?

**Comment by tomstgeorge** [comment]
Latest version of Chrome on MacOS- Version 73.0.3683.86 (Official Build) (64-bit)

The update value is saved, but the update is not shown when you reopen the block after publishing the page. Instead, it shows the previous value of the date field. 

Even if you publish the block (at which point it's still good) before you publish the page the value displayed is wrong when you reopen the block.

![Mar-24-2019 16-02-18](https://user-images.githubusercontent.com/2531109/54885839-aab64b80-4e4e-11e9-941b-211225f148ce.gif)

**Comment by tomstgeorge** [comment]
Re: issue with date field. 

Should I open a new ticket, this is causing client no end of problems.

**Comment by ScopeyNZ** [comment]
Ah yep - Admittedly this fell off my radar. I've raised an issue from your last message for you 🙂
